### ISSUE TITLE
Einfache Berechnung des Notendurchschnitts

### ISSUE THREAD

**Issue by JannikZed** [dersvenhesse/ios-grades#1]
Hallo,
es sollte eine Möglichkeit geben, den Notendurchschnitt auch ohne Credit-Gewichtung ausrechnen zu lassen. Bei meinem Studiengang an der HfTL wird der Schnitt so berechnet

**Comment by dersvenhesse** [comment]
Eine automatische Erkennung der benötigten Berechnung ist leider nicht möglich, da dies von Hochschule zu Hochschule und je nach Studiengang abweicht. 

Vorstellbar ist jedoch eine Einstellmöglichkeit, ob der normale Durchschnitt oder der Schnitt mit gewichteten CP berechnet werden soll.

Angenommen man hat drei Noten:
- 1,7 mit 10 CP
- 2,3 mit 5 CP
- 2,7 mit 3 CP

Berechnung nach gewichteten CP: (1,7 \* 10 + 2,3 \* 5 + 2,7 \* 3) / (10 + 5 + 3) = 2,03
Normaler Durchschnitt: (1,7 + 2,3 + 2,7) / 3 = 2,23

Ist im konkreten Fall letzteres die gewünschte Berechnungsart?

**Comment by JannikZed** [comment]
Ja richtig, ich denke eine Einstellmöglichkeit wäre eine gute Option. 
Die untere Berechnungsart ist genau richtig.

Schöne Grüße

**Comment by dersvenhesse** [comment]
Eine entsprechende Lösung ist nun vorgesehen und wird mit dem nächsten Release veröffentlicht – ich warte noch auf Feedback bzgl. eines kleinen Bugs und würde den Fix dann mitsamt dieses Features veröffentlichten.

Besteht Interesse an einem Beta-Test der Funktion via TestFlight? Wenn ja, bräuchte ich eine E-Mail-Adresse, sodass ich einen Tester hinzufügen kann.

**Comment by JannikZed** [comment]
super, klingt gut! Ich bin zufrieden mit dem Update, sobald es veröffentlicht wird. Falls du aber noch einen Tester brauchst, bin ich natürlich bereit mir das ganze genauer anzuschauen: zinkljannik@gmail.com

**Comment by dersvenhesse** [comment]
Die Version 2016.09.10 mit dieser Anpassung sollte in den nächsten Tagen als Update freigegeben werden.
