### ISSUE TITLE
HSRM Login funktioniert nicht mehr

### ISSUE THREAD

**Issue by balu94** [dersvenhesse/ios-grades#6]
Seit der Umstellung des qis auf den compass funktioniert der Login nicht mehr. 

https://compass.hs-rm.de/

**Comment by dersvenhesse** [comment]
Die HSRM nutzt die Notenfunktionalität von Compass aktuell noch nicht, sondern hat dort temporär das QIS eingebettet – es gilt also jetzt eine Übergangslösung bauen und dann nach der finalen Umstellung seitens der HSRM einem Komplett-Umbau zur Unterstützung von Compass (bzw. HISinOne) zu beginnen. Der Umfang dieser Anpassungen lässt sich aktuell nicht abschätzen.

Leider habe ich selbst derzeit etwas Zeitmangel, sodass ich mich nicht darum kümmern kann. Aus diesem Grund habe ich Grades auch vorübergehend aus dem App Store entfernt. Sofern PRs eingereicht werden, kann ich diese allerdings gerne kurz prüfen und mergen.
